### ISSUE TITLE
注册提示用户名已存在，登录提示‘500’

### ISSUE THREAD

**Issue by muYoz** [wdsjxh/fiddler_tools#1]
如图所示
![image](https://user-images.githubusercontent.com/24564618/127759409-2ef9c46a-d3fb-4c74-b0b5-c1f7ba95d2c2.png)

**Comment by muYoz** [comment]
![image](https://user-images.githubusercontent.com/24564618/127759442-4acf1808-d471-464b-ba86-a58b4f043443.png)

**Comment by muYoz** [comment]
安装环境：
-win10+desk docker+mysql5.6.42
安装方式：
-源码构建docker安装

**Comment by muYoz** [comment]
问题已解决，是导入数据库未注意报错：
ERROR 1709 (HY000): Index column size too large. The maximum column size is 767 bytes.
msyql修改即可：
mysql> set global innodb_file_format = BARRACUDA;
Query OK, 0 rows affected (0.00 sec)

mysql> set global innodb_large_prefix = ON;
Query OK, 0 rows affected (0.00 sec)

**Comment by ssunadmin** [comment]
> 安装环境： -win10+desk docker+mysql5.6.42 安装方式： -源码构建dock
您安装成功了吗

**Comment by ssunadmin** [comment]
> 安装环境： -win10+desk docker+mysql5.6.42 安装方式： -源码构建docker安装

想问下您搭建成功了吗？能留下联系方式吗或者加我QQ（807965684），一直没部署好

**Comment by wdsjxh** [comment]
稍等



---Original---
From: ***@***.***&gt;
Sent at: 2021年12月9日(Thu) Evening7:46
To: ***@***.***&gt;;
Cc: ***@***.***&gt;;
Subject: Re: [wdsjxh/fiddler_tools] 注册提示用户名已存在，登录提示‘500’ (#1)




  
安装环境： -win10+desk docker+mysql5.6.42 安装方式： -源码构建docker安装
  
想问下您搭建成功了吗？能留下联系方式吗或者加我QQ（807965684），一直没部署好
 
—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
